WAIT_SECONDS = 20
PAGINATION_MAX_ATTEMPTS = 3
PAGINATION_CLICK_SETTLE_SECONDS = 1.0
PAGINATION_CHANGE_TIMEOUT_SECONDS = 4.0
PAGINATION_POLL_INTERVAL_SECONDS = 0.2
PAGINATION_BETWEEN_PAGES_SECONDS = 0.35

# URLS
EQUITY_SCREENER_URL = "https://finance.yahoo.com/research-hub/screener/equity/"
